syntax = "proto2";

package enchant;

option java_package = "org.enchant.protos";
option java_outer_classname = "EnvelopeProtos";

message Envelope {
    enum Type {
        UNKNOWN = 0;
        DOUBLE_RATCHET = 1;
        PREKEY_MESSAGE = 3;
        SERVER_DELIVERY_RECEIPT = 5;
        UNIDENTIFIED_SENDER = 6;
        PLAINTEXT_CONTENT = 8;
    }

    optional Type type = 1;
    optional string sourceServiceId = 11;
    optional uint32 sourceDeviceId = 7;
    optional string destinationServiceId = 13;
    optional uint64 clientTimestamp = 5;
    optional bytes content = 8;
    optional string serverGuid = 9;
    optional uint64 serverTimestamp = 10;
    optional bool ephemeral = 12;
    optional bool urgent = 14 [default = true];
    optional string updatedPni = 15;
    optional bool story = 16;
    optional bytes reportSpamToken = 17;
    optional bytes sourceServiceIdBinary = 19;
    optional bytes destinationServiceIdBinary = 20;
    optional bytes serverGuidBinary = 21;
    optional bytes updatedPniBinary = 22;
}
