package org.enchant.navigation

sealed class NavRoute {
    data object Splash : NavRoute()
    data object Welcome : NavRoute()
    data object PhoneEntry : NavRoute()
    data object OtpVerify : NavRoute()
    data object Permissions : NavRoute()
    data object ProfileSetup : NavRoute()
    data object UsernamePicker : NavRoute()
    data object KeyGeneration : NavRoute()
    data object PinCreation : NavRoute()
    data object RestorePrompt : NavRoute()
    data object ChatList : NavRoute()
    data object CallLog : NavRoute()
    data object StatusFeed : NavRoute()
    data object ChannelsFeed : NavRoute()
    data object Settings : NavRoute()
    data class Conversation(val conversationId: String) : NavRoute()
    data class Search(val conversationId: String? = null) : NavRoute()
    data class IncomingCall(val callId: String) : NavRoute()
    data class OutgoingCall(val userId: String) : NavRoute()
    data class ActiveVoiceCall(val callId: String) : NavRoute()
    data class ActiveVideoCall(val callId: String) : NavRoute()
    data class GroupCall(val callId: String) : NavRoute()
    data object Groups : NavRoute()
    data class GroupInfo(val groupId: String) : NavRoute()
    data object CreateGroup : NavRoute()
    data object Contacts : NavRoute()
    data object StatusCreate : NavRoute()
    data class StatusViewer(val statusId: String) : NavRoute()
    data object AccountSettings : NavRoute()
    data object SecuritySettings : NavRoute()
    data object PrivacySettings : NavRoute()
    data object NotificationSettings : NavRoute()
    data object AppearanceSettings : NavRoute()
    data object ChatsSettings : NavRoute()
    data object StorageSettings : NavRoute()
    data object About : NavRoute()
    data object BackupSettings : NavRoute()
    data object BlockedUsers : NavRoute()
    data object AppLock : NavRoute()
    data object Stickers : NavRoute()
    data class PollCreate(val conversationId: String) : NavRoute()
    data object LocationPicker : NavRoute()
    data object ShareTarget : NavRoute()
    data object QrCode : NavRoute()
    data object QrScanner : NavRoute()
    data class MediaViewer(val conversationId: String) : NavRoute()
}
