#ifndef ENCHANT_ERROR_H
#define ENCHANT_ERROR_H

#include <cstdint>

namespace enchant {

enum class Error : int {
    SUCCESS = 0,

    NULL_POINTER = -1,
    BUFFER_TOO_SMALL = -2,
    INVALID_KEY_SIZE = -3,
    INVALID_NONCE_SIZE = -4,
    CIPHERTEXT_TOO_SHORT = -5,
    DECRYPTION_FAILED = -6,
    SIGNATURE_INVALID = -7,
    KEY_EXPIRED = -8,
    REPLAY_DETECTED = -9,
    OUT_OF_BOUNDS = -10,
    INVALID_FORMAT = -11,
    NOT_IMPLEMENTED = -12,
    INTERNAL = -99,

    NO_SESSION = -100,
    DUPLICATE_MESSAGE = -101,
    MAX_SKIPPED_KEYS = -102,
    PREKEY_CONSUMED = -103,
    PREKEY_NOT_FOUND = -104,
    EPOCH_MISMATCH = -105,
    REGISTRATION_MISMATCH = -106,
    SESSION_STATE_INVALID = -107,
    UNTRUSTED_IDENTITY = -108,
    INVALID_SESSION_STRUCTURE = -109,
    UNRECOGNIZED_MESSAGE_VERSION = -110,
    INVALID_PROTOBUF_ENCODING = -111,

    LEGACY_MESSAGE = -112,
    INVALID_KEY_ID = -113,
    INVALID_VERSION = -114,
    INVALID_REGISTRATION_ID = -115,
    INVALID_SESSION = -116,
    SELF_SEND = -117,

    MISMATCHED_DEVICES = -200,
    MISSING_DEVICES = -201,
    EXTRA_DEVICES = -202,
    STALE_DEVICES = -203
};

constexpr inline int to_int(Error e) { return static_cast<int>(e); }

}

#define ENCHANT_SUCCESS                    0
#define ENCHANT_ERROR_NULL_POINTER        -1
#define ENCHANT_ERROR_BUFFER_TOO_SMALL    -2
#define ENCHANT_ERROR_INVALID_KEY_SIZE    -3
#define ENCHANT_ERROR_INVALID_NONCE_SIZE  -4
#define ENCHANT_ERROR_CIPHERTEXT_TOO_SHORT -5
#define ENCHANT_ERROR_DECRYPTION_FAILED   -6
#define ENCHANT_ERROR_SIGNATURE_INVALID   -7
#define ENCHANT_ERROR_KEY_EXPIRED         -8
#define ENCHANT_ERROR_REPLAY_DETECTED     -9
#define ENCHANT_ERROR_OUT_OF_BOUNDS       -10
#define ENCHANT_ERROR_INVALID_FORMAT      -11
#define ENCHANT_ERROR_NOT_IMPLEMENTED     -12
#define ENCHANT_ERROR_INTERNAL            -99

#define ENCHANT_ERROR_NO_SESSION          -100
#define ENCHANT_ERROR_DUPLICATE_MESSAGE   -101
#define ENCHANT_ERROR_MAX_SKIPPED_KEYS    -102
#define ENCHANT_ERROR_PREKEY_CONSUMED     -103
#define ENCHANT_ERROR_PREKEY_NOT_FOUND    -104
#define ENCHANT_ERROR_EPOCH_MISMATCH      -105
#define ENCHANT_ERROR_REGISTRATION_MISMATCH -106
#define ENCHANT_ERROR_SESSION_STATE_INVALID -107
#define ENCHANT_ERROR_UNTRUSTED_IDENTITY -108
#define ENCHANT_ERROR_INVALID_SESSION_STRUCTURE -109
#define ENCHANT_ERROR_UNRECOGNIZED_MESSAGE_VERSION -110
#define ENCHANT_ERROR_INVALID_PROTOBUF_ENCODING -111

#define ENCHANT_ERROR_LEGACY_MESSAGE         -112
#define ENCHANT_ERROR_INVALID_KEY_ID         -113
#define ENCHANT_ERROR_INVALID_VERSION        -114
#define ENCHANT_ERROR_INVALID_REGISTRATION_ID -115
#define ENCHANT_ERROR_INVALID_SESSION        -116
#define ENCHANT_ERROR_SELF_SEND              -117

#define ENCHANT_ERROR_MISMATCHED_DEVICES     -200
#define ENCHANT_ERROR_MISSING_DEVICES        -201
#define ENCHANT_ERROR_EXTRA_DEVICES          -202
#define ENCHANT_ERROR_STALE_DEVICES          -203

#endif