#ifndef ENCHANT_VEIL_ERROR_HPP
#define ENCHANT_VEIL_ERROR_HPP

namespace enchant {
namespace veil {

enum class VeilError : int {
    SUCCESS = 0,

    NULL_POINTER = -1,
    BUFFER_TOO_SMALL = -2,
    INVALID_KEY_SIZE = -3,
    INVALID_NONCE_SIZE = -4,
    CIPHERTEXT_TOO_SHORT = -5,
    DECRYPTION_FAILED = -6,
    SIGNATURE_INVALID = -7,
    KEY_EXPIRED = -8,
    REPLAY_DETECTED = -9,
    OUT_OF_BOUNDS = -10,
    INVALID_FORMAT = -11,
    NOT_IMPLEMENTED = -12,
    INTERNAL = -99,

    NO_SESSION = -100,
    DUPLICATE_MESSAGE = -101,
    MAX_SKIPPED_KEYS = -102,
    PREKEY_CONSUMED = -103,
    PREKEY_NOT_FOUND = -104,
    EPOCH_MISMATCH = -105,
    REGISTRATION_MISMATCH = -106,
    SESSION_STATE_INVALID = -107,
    UNTRUSTED_IDENTITY = -108,
    INVALID_SESSION_STRUCTURE = -109,
    UNRECOGNIZED_MESSAGE_VERSION = -110,
    INVALID_PROTOBUF_ENCODING = -111,

    TRUST_ROOT_INVALID = -200,
    CERTIFICATE_EXPIRED = -201,
    CERTIFICATE_SIGNATURE_INVALID = -202,
    UNKNOWN_VERSION = -203,
    SELF_SEND = -204,
    SERVER_CERTIFICATE_UNKNOWN = -205
};

constexpr inline int to_int(VeilError e) { return static_cast<int>(e); }

}
}

#define ENCHANT_VEIL_SUCCESS                          0
#define ENCHANT_VEIL_ERROR_NULL_POINTER             -1
#define ENCHANT_VEIL_ERROR_BUFFER_TOO_SMALL         -2
#define ENCHANT_VEIL_ERROR_INVALID_KEY_SIZE          -3
#define ENCHANT_VEIL_ERROR_INVALID_NONCE_SIZE       -4
#define ENCHANT_VEIL_ERROR_CIPHERTEXT_TOO_SHORT     -5
#define ENCHANT_VEIL_ERROR_DECRYPTION_FAILED        -6
#define ENCHANT_VEIL_ERROR_SIGNATURE_INVALID        -7
#define ENCHANT_VEIL_ERROR_KEY_EXPIRED             -8
#define ENCHANT_VEIL_ERROR_REPLAY_DETECTED          -9
#define ENCHANT_VEIL_ERROR_OUT_OF_BOUNDS           -10
#define ENCHANT_VEIL_ERROR_INVALID_FORMAT           -11
#define ENCHANT_VEIL_ERROR_NOT_IMPLEMENTED         -12
#define ENCHANT_VEIL_ERROR_INTERNAL                -99
#define ENCHANT_VEIL_ERROR_NO_SESSION              -100
#define ENCHANT_VEIL_ERROR_DUPLICATE_MESSAGE       -101
#define ENCHANT_VEIL_ERROR_MAX_SKIPPED_KEYS        -102
#define ENCHANT_VEIL_ERROR_PREKEY_CONSUMED          -103
#define ENCHANT_VEIL_ERROR_PREKEY_NOT_FOUND        -104
#define ENCHANT_VEIL_ERROR_EPOCH_MISMATCH          -105
#define ENCHANT_VEIL_ERROR_REGISTRATION_MISMATCH    -106
#define ENCHANT_VEIL_ERROR_SESSION_STATE_INVALID    -107
#define ENCHANT_VEIL_ERROR_UNTRUSTED_IDENTITY      -108
#define ENCHANT_VEIL_ERROR_INVALID_SESSION_STRUCTURE -109
#define ENCHANT_VEIL_ERROR_UNRECOGNIZED_MESSAGE_VERSION -110
#define ENCHANT_VEIL_ERROR_INVALID_PROTOBUF_ENCODING -111
#define ENCHANT_VEIL_ERROR_TRUST_ROOT_INVALID      -200
#define ENCHANT_VEIL_ERROR_CERTIFICATE_EXPIRED     -201
#define ENCHANT_VEIL_ERROR_CERTIFICATE_SIGNATURE_INVALID -202
#define ENCHANT_VEIL_ERROR_UNKNOWN_VERSION         -203
#define ENCHANT_VEIL_ERROR_SELF_SEND               -204
#define ENCHANT_VEIL_ERROR_SERVER_CERTIFICATE_UNKNOWN -205

#endif